version: '3'
services:
  mongo:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - "27017:27017"
    networks:
      - digital-wallet-network
    command: ["--bind_ip", "0.0.0.0"]
  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - digital-wallet-network
  digital-wallet:
    container_name: digital-wallet
    build:
      context: .
      dockerfile: Dockerfile
    image: digital-wallet:latest
    ports:
      - "8888:8080"
    depends_on:
      - mongo
      - rabbitmq
    networks:
      - digital-wallet-network
networks:
  digital-wallet-network:
    driver: bridge