# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.2
jobs:
  sonar-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - sonarcloud/scan
workflows:
  build-workflow:
    jobs:
      - sonar-job
